### ISSUE TITLE
Can you open source the visualization part of the code?

### ISSUE THREAD

**Issue by FriedaSmith** [jymoon0613/m2former#1]
Hi, I appreciate your work very much. Can you open source the visualization part of the code?

**Comment by jymoon0613** [comment]
Hi, thank you for your interest in my paper.

I have the visualization code in a juptyper notebook, not a python script.

It takes some time to change it to a readable way.

Unfortunately, I don't have time at the moment due to personal commitments.

If you wait just a little longer, I'll provide it to you as soon as possible.

2023년 11월 15일 (수) 오전 11:39, FriedaSmith ***@***.***>님이 작성:

**Comment by FriedaSmith** [comment]
Thank you for your reply. If you are busy and don't have time, you can also upload a Jumpyper Notebook, and I will make modifications according to the task myself.

**Comment by jymoon0613** [comment]
I simply updated it with a python script. You can conduct the visualization as follows:

`python visualize.py --gpu_ids {GPU_IDs} --pretrained_model {PATH/TO/PRETRAINED_MODEL}`

I'll add comments to the code later to improve readability. I hope this is helpful to you :)

**Comment by FriedaSmith** [comment]
Thank you very kindly.

**Comment by FriedaSmith** [comment]
Sorry to bother you again, the **save_image()** is not defined in `visualize.py`

`
 save_image(sample, "mask/{}.png".format(step), nrow=1, normalize=True)
`

**Comment by FriedaSmith** [comment]
> Sorry to bother you again, the **save_image()** is not defined in `visualize.py`
> 
> `save_image(sample, "mask/{}.png".format(step), nrow=1, normalize=True)`

It should be `from torchvision.utils import save_image`, right?

**Comment by jymoon0613** [comment]
Oh, that's right. That line seems to be missing. Thanks for noticing me :)
